name: Create Release

on:
  push:
    tags:
      - 'v*.*.*'
      - '*.*.*'

permissions:
  contents: write

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Extract version from tag
        id: version
        run: |
          # Remove 'v' prefix if present
          VERSION=${GITHUB_REF_NAME#v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "Version extracted: $VERSION"

      - name: Extract changelog for version
        id: changelog
        run: |
          VERSION="${{ steps.version.outputs.version }}"
          echo "Extracting changelog for version $VERSION"
          
          # Extract the section for this version from CHANGELOG.md
          # This uses awk to find the section between ## [$VERSION] and the next ## [
          CHANGELOG_CONTENT=$(awk -v version="$VERSION" '
            /^## \[/ {
              if (found) exit;
              if ($0 ~ "\\[" version "\\]") {
                found=1;
                next;
              }
            }
            found { print }
          ' CHANGELOG.md)
          
          if [ -z "$CHANGELOG_CONTENT" ]; then
            echo "::error::Could not find changelog entry for version $VERSION"
            exit 1
          fi
          
          # Save to file to preserve formatting
          echo "$CHANGELOG_CONTENT" > /tmp/changelog.txt
          echo "Changelog extracted successfully"

      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        with:
          body_path: /tmp/changelog.txt
          draft: false
          prerelease: false
          name: Release ${{ steps.version.outputs.version }}
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
